name: visitors thoughts workflow

on:
  issues:
    types: [opened]
  schedule:
    - cron: '0 0 */2 * *'

env:
  BLOG_API_URL: ${{ secrets.BLOG_API_URL }}

jobs:
  update-my-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: run python script
        run: python runscript.py
      
      - name: Update README
        run: |
          echo "${{ github.event.issue.user.login }}" 
          git config --local user.email github-actions[bot]
          git config --local user.name  github-actions[bot]@users.noreply.github.com
          git add Readme.md
          git commit -m "Update README with issue owner"
          git push origin HEAD:main
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-blog-post:
    runs-on: ubuntu-latest
    env:
      BLOG_API_URL: ${{ secrets.BLOG_API_URL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch and Update Blog Post
        run: python update-blog-post.py

      - name: Commit and Push Blog Post Update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Readme.md
          git commit -m "Add new blog post to README"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}